# Base configs
baseurl: "https://photography.prateekj117.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Prateek Jain"
subtitle: "See the world through my eyes!"
author: "Prateek Jain"
header:
 title: "Photography"
 subtitle: "by Prateek"
footer:
 name: "Hey there, my name is Prateek"
 bio: "Developer and learning Photography."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/prateekj117"
  twitter: "https://www.twitter.com/prateekj117"
  instagram: "https://www.instagram.com/prateekj117"
  linkedin: "https://in.linkedin.com/in/prateekj117"
  github: "https://www.github.com/prateekj117"
